###GET Users
# @timeout 600 m

GET http://localhost:8000/public/index.php/user
Accept: application/ld+json


###GET MatchTypes
# @timeout 600 m
GET http://localhost:8000/public/index.php/match_type
Accept: application/ld+json
