###Login
# @timeout 600 m
# @no-cookie-jar
POST http://localhost:8000/public/index.php/login
Accept: application/ld+json
Content-Type: application/ld+json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###GET Users
# @timeout 600 m
# @no-cookie-jar
GET http://localhost:8000/public/index.php/user
Accept: application/ld+json
Cookie: {{cookie}}

###Create User
# @timeout 600 m
# @no-cookie-jar
POST http://localhost:8000/public/index.php/user/register
Accept: application/ld+json
Content-Type: application/ld+json

{
  "user": {
    "username" : "{{username}}",
	"firstName": "Dank",
	"lastName": "Yoda",
    "email" : "dank@gmail.com",
    "titles" : "",
    "guns" : "",
    "optics" : "",
    "ammo" : "",
    "instagramHandle" : "",
    "bio" : ""
  },
  "plainPassword": "{{password}}"
}


###GET MatchTypes
# @timeout 600 m
# @no-cookie-jar
GET http://localhost:8000/public/index.php/match_type
Accept: application/ld+json
Cookie: {{cookie}}
